Djangoyunweiguanli/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf.urls import url
from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^hostlist/$', views.HostView.as_view(), name='host'),
    url(r'^host/(?P<pk>[0-9]+)/edit/$', views.HostEditView.as_view(), name='host_edit'),
    url(r'^host/(?P<pk>[0-9]+)/$', views.HostDetailView.as_view(), name='host_detail'),
    url(r'^new/$', views.HostCreateView.as_view(), name='host_new'),
    url(r'^host/(?P<id>[a-z]+)/(?P<pk>[0-9]+)/$', views.HostFilterView.as_view(), name='host_filter'),

]

app/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


# 主机的分类

class HostCategorys(models.Model):
    name = models.CharField(max_length=70, verbose_name='主机分类名')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "主机分类"
        verbose_name_plural = verbose_name


# 主机的分组（所在资源池）
class HostGroups(models.Model):
    name = models.CharField(max_length=70, verbose_name='主机属组名')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "主机属组"
        verbose_name_plural = verbose_name

# 操作系统分类

class OperatingSystems(models.Model):
    name = models.CharField(max_length=30, verbose_name='主机操作系统')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "主机操作系统"
        verbose_name_plural = verbose_name

# 主机的使用状态（在用，停用，等）
class Host_status(models.Model):
    name = models.CharField(max_length=10, verbose_name='主机状态')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "主机状态"
        verbose_name_plural = verbose_name

# 主机的种类（物理机，虚拟机）

class Host(models.Model):
    # IP地址
    ip = models.GenericIPAddressField(verbose_name="IP地址", max_length=20)
    # 主机名
    host_name = models.CharField(max_length=20, verbose_name='主机名')
    # 主机的用途,可以为空
    host_purpose = models.CharField(max_length=20, blank=True, verbose_name='用途')
    # 主机的使用状态 和 Host_status 对应
    host_status = models.ForeignKey(Host_status, verbose_name='状态')
    # 主机的分类，和 HostCateorys 一对一
    Host_category = models.ForeignKey(HostCategorys, verbose_name='分类')
    # 主机的所属组，和HostGroups 一对一
    Host_group = models.ForeignKey(HostGroups, verbose_name='属组')
    # 主机的操作系统类型
    Host_operatingsystem = models.ForeignKey(OperatingSystems, verbose_name='操作系统')
    # 管理员账号
    admin_Account = models.CharField(max_length=20, blank=True, verbose_name='管理员账号')
    # 管理员密码
    admin_password = models.CharField(max_length=20, blank=True, verbose_name='管理员密码')
    # 主机的详细信息备注
    Host_body = RichTextUploadingField(blank=True, verbose_name='备注')
    # 创建和最后一次修改时间
    # auto_now_add 当对象第一次被创建时自动设置当前时间
    # auto_now     每次保存对象时，自动设置该字段为当前时间。用于"最后一次修改"的时间戳
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 这个方法用来生产url
    def get_absolute_url(self):
        return reverse('app:host_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.host_name

    class Meta:
        verbose_name = "主机信息"
        verbose_name_plural = verbose_name

class HostComment(models.Model):
    host = models.ForeignKey(Host, related_name='hostcomments')
    body = models.CharField(max_length=100, verbose_name='添加操作记录')
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=20, default='admin')

    def __str__(self):
        return 'Comment {} {} on {}'.format(self.host, self.body, self.created)

    class Meta:
        ordering = ('-created',)
        verbose_name = "主机操作记录"
        verbose_name_plural = verbose_name

app/forms.py
from django import forms
from .models import Host, HostComment
from django.forms import TextInput, Select


class PostForm(forms.ModelForm):
    class Meta:
        model = Host
        fields = ('ip', 'host_name', 'host_purpose', 'Host_category', 'Host_group',
                  'admin_Account', 'admin_password', 'Host_operatingsystem', 'Host_body', 'host_status')

        # 重写（覆盖）默认的字段 http://python.usyiyi.cn/translate/django_182/topics/forms/modelforms.html
        # 给title 添加了一个 css class类名
        widgets = {
            'host_name': TextInput(attrs={'class': 'form-control'}),
            'host_purpose': TextInput(attrs={'class': 'form-control'}),
            'Host_category': Select(attrs={'class': 'form-control'}),
            'Host_operatingsystem': Select(attrs={'class': 'form-control'}),
        }


class HostCommentForm(forms.ModelForm):
    class Meta:
        model = HostComment
        fields = ('body',)

        widgets = {
            'body': TextInput(attrs={'class': 'form-test'}),
        }

app/views.py
from .models import Host, HostGroups, Host_status, HostCategorys, HostComment
from .forms import PostForm, HostCommentForm
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic.base import View


# 基于类的首页视图  (访问控制 @login_required 登录后才可访问该视图  基于类的实现)
class IndexView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = HostComment
    context_object_name = 'host_comment_list'
    template_name = 'app/index.html'

    def get_queryset(self):
        return HostComment.objects.all()[0:5:1]


# 基于类的首页视图  (访问控制 @login_required 登录后才可访问该视图  基于类的实现)
class HostView(LoginRequiredMixin, ListView):
    # login_url = '/accounts/login/'
    # redirect_field_name = 'redirect_to'
    model = Host
    context_object_name = 'post_list'
    template_name = 'app/host.html'


# host详情视图

class HostDetailView(DetailView):
    model = Host
    template_name = 'app/host_detail.html'
    context_object_name = 'post'

    def post(self, request, *args, **kwargs):
        response = super(HostDetailView, self).get(request, *args, **kwargs)
        comment_form = HostCommentForm(data=self.request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.host = self.object
            new_comment.author = self.request.user
            new_comment.save()
        return response


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_form = HostCommentForm()
        comments = self.object.hostcomments.all()
        context['comments'] = comments
        context['comment_form'] = comment_form
        return context




# 基于类的 编辑更新数据视图

class HostEditView(UpdateView):
    model = Host
    form_class = PostForm
    template_name = 'app/host_edit.html'


# 基于类的创建数据视图

class HostCreateView(CreateView):
    form_class = PostForm
    template_name = 'app/host_edit.html'

# 分组筛选host的类
# url 接受两个参数 第一个 是 筛选的选项  group status category  第2个参数是 具体筛选的内容的 pk
class HostFilterView(ListView):
    model = Host
    template_name = 'app/host.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        id=self.kwargs.get('id')
        if id == 'group':
            hostgroup = get_object_or_404(HostGroups, pk=self.kwargs.get('pk'))
            return super(HostFilterView, self).get_queryset().filter(Host_group=hostgroup)
        elif id == 'status':
            host_status = get_object_or_404(Host_status, pk=self.kwargs.get('pk'))
            return super(HostFilterView, self).get_queryset().filter(host_status=host_status)
        elif id == 'category':
            host_category = get_object_or_404(HostCategorys, pk=self.kwargs.get('pk'))
            return super(HostFilterView, self).get_queryset().filter(Host_category=host_category)

templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>运维平台</title>

    <meta name="description" content="bootstrap grid sizing"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'app/font-awesome/4.5.0/css/font-awesome.min.css' %}"/>

    <!-- page specific plugin styles -->

    <!-- text fonts -->
    <link rel="stylesheet" href="{% static 'app/css/fonts.googleapis.com.css' %}"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="{% static 'app/css/ace.min.css' %}" class="ace-main-stylesheet" id="main-ace-style"/>


    <link rel="stylesheet" href="{% static 'app/css/ace-skins.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'app/css/ace-rtl.min.css' %}"/>


    <script src="{% static 'app/js/ace-extra.min.js' %}"></script>
    <script src="{% static 'app/js/echarts.js' %}"></script>

    <style>
        .page-content {
            padding: 1px 1px 1px;
        }

        .panel-body {
            padding: 0px;
        }

        .form-test {
            margin-left: 12px;
            margin-top: 5px;
            width: 40%;
        }

    </style>
</head>

<body class="no-skin">
<div id="navbar" class="navbar navbar-default">
    <div class="navbar-container" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="{% url 'app:index' %}" class="navbar-brand">
                <small>
                    <i class="fa fa-leaf"></i>
                    运维信息管理平台
                </small>
            </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="light-blue">
                    <a href="{% url 'account_logout' %}">
                        <span class="user-info">
                            <small>{{ user.username }}已登录/注销</small>
                        </span>
                    </a>
            </ul>
            </li>
        </div>
    </div><!-- /.navbar-container -->
</div>

<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>

    {#            左侧导航栏#}
    <div id="sidebar" class="sidebar                  responsive                    ace-save-state">
        <script type="text/javascript">
            try {
                ace.settings.loadState('sidebar')
            } catch (e) {
            }
        </script>

        <ul class="nav nav-list">
            <li class="">
                <a href="{% url 'app:index' %}">
                    <i class="menu-icon fa fa-tachometer"></i>
                    <span class="menu-text"> 控制中心 </span>
                </a>
                <b class="arrow"></b>
            </li>
            <li class="">
                <a href="{% url 'app:host' %}">
                    <i class="menu-icon fa fa-desktop"></i>
                    <span class="menu-text"> 服务器信息 </span>
                </a>
                <b class="arrow"></b>
            </li>
        </ul><!-- /.nav-list -->

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>

    <div class="main-content">

        {% block main %}
        {% endblock main %}
    </div><!-- /.main-content -->


    {#            底部信息栏#}
    <div class="footer">
        <div class="footer-inner">
            <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Rokin</span>
							Application &copy; 2017-2020
						</span>

                &nbsp; &nbsp;
                <span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
            </div>
        </div>
    </div>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->
</body>

</html>

templates/app/host_detail.html
{% extends 'app/base.html' %}
{% load staticfiles %}


{% block main %}

    <div class="table-detail">
        <div class="row">
            <div class="col-xs-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">服务器信息</div>
                    <div class="panel-body">

                        <div class="space visible-xs"></div>
                        <div class="profile-user-info profile-user-info-striped">
                            <div class="profile-info-row">
                                <div class="profile-info-name"> IP地址</div>
                                <div class="profile-info-value">
                                    <span>{{ post.ip }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 主机名</div>
                                <div class="profile-info-value">
                                    <span>{{ post.host_name }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 用途</div>
                                <div class="profile-info-value">
                                    <span>{{ post.host_purpose }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 分类</div>
                                <div class="profile-info-value">
                                    <span>{{ post.Host_category }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 状态</div>
                                <div class="profile-info-value">
                                    <span>{{ post.host_status }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 所属组</div>
                                <div class="profile-info-value">
                                    <span class="label label-sm label-warning">{{ post.Host_group }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 操作系统</div>
                                <div class="profile-info-value">
                                    <span class="label label-sm label-warning">{{ post.Host_operatingsystem }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> admin账号</div>
                                <div class="profile-info-value">
                                    <span>{{ post.admin_Account }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> admin密码</div>
                                <div class="profile-info-value">
                                    <span>{{ post.admin_password }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 创建时间</div>
                                <div class="profile-info-value">
                                    <span>{{ post.created_time }}</span>
                                </div>
                            </div>
                            <div class="profile-info-row">
                                <div class="profile-info-name"> 最后修改时间</div>
                                <div class="profile-info-value">
                                    <span>{{ post.modified_time|timesince }} 前</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-white btn-info btn-bold">
                    <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
                    <a href="{% url 'app:host_edit' pk=post.pk %}">编辑</a>
                </button>
            </div>
            <div class="col-xs-8">
                <div class="panel panel-warning">
                    <div class="panel-heading">备注信息</div>
                    <div class="panel-body">
                        {{ post.Host_body|safe }}
                    </div>
                </div>
                <div class="panel panel-warning">
                    <div class="panel-heading">操作记录</div>
                    <div class="panel-body">
                        {#操作记录输入框#}
                        <form action="{{ post.get_absolute_url }}" method="post">
                            {{ comment_form.body }}
                            {{ comment_form.body.errors }}
                            <button type="submit" class="btn btn-white btn-info btn-bold">
                                <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
                                添加操作记录
                            </button>{% csrf_token %}
                        </form>
                        {#操作记录显示框#}
                        <div class="profile-user-info profile-user-info-striped">
                            <div>
                                <table class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th class="center">时间</th>
                                        <th class="center">IP地址</th>
                                        <th class="center">用户</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for comment in comments %}
                                        <tr>
                                            <td class="center">{{ comment.created|timesince }} 前</td>

                                            <td>
                                                {{ comment.body|linebreaks }}
                                            </td>
                                            <td>{{ comment.author }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

templates/app/index.html
{% extends 'app/base.html' %}
{% load staticfiles %}
{% load host_tags %}

{% block main %}
    <div class="table-detail">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-warning">
                <div class="panel-heading">服务器统计信息</div>
                <div class="panel-body">
                    <div class="profile-user-info profile-user-info-striped">
                        <div class="row">
                            <div class="col-sm-4">
                                {% get_group as group_list %}
                                {% for Group in group_list %}
                                    <div class="infobox infobox-green">
                                        <div class="infobox-icon">
                                            <!--将节点图表更改成 home，之后的雷同-->
                                            <i class="ace-icon fa fa-home"></i>
                                        </div>

                                        <div class="infobox-data">
                                            <span class="infobox-data-number">{{ Group.num_posts }}</span>
                                            <a href="{% url 'app:host_filter' 'group' Group.pk  %}">{{ Group.name }} 服务器</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-sm-4">
                                {% get_status as status_list %}
                                {% for Status in status_list %}
                                    <div class="infobox infobox-green">
                                        <div class="infobox-icon">
                                            <!--将节点图表更改成 home，之后的雷同-->
                                            <i class="ace-icon fa fa-edit"></i>
                                        </div>

                                        <div class="infobox-data">
                                            <span class="infobox-data-number">{{ Status.num_posts }}</span>
                                            <a href="{% url 'app:host_filter' 'status' Status.pk %}">{{ Status.name }}</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-sm-4">

                                {% get_categorys as categorys_list %}
                                {% for Categorys in categorys_list %}
                                    <div class="infobox infobox-green">
                                        <div class="infobox-icon">
                                            <!--将节点图表更改成 home，之后的雷同-->
                                            <i class="ace-icon fa fa-home"></i>
                                        </div>

                                        <div class="infobox-data">
                                            <span class="infobox-data-number">{{ Categorys.num_posts }}</span>
                                            <a href="{% url 'app:host_filter' 'category' Categorys.pk %}">{{ Categorys.name }}</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel panel-warning">
                <div class="panel-heading">最近操作记录</div>
                <div class="panel-body">
                    <div class="profile-user-info profile-user-info-striped">
                        <div>
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th class="center">时间</th>
                                    <th>IP地址</th>
                                    <th class="hidden-xs">操作</th>
                                    <th class="hidden-480">主机名</th>
                                    <th>用户</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for host_comment in host_comment_list %}
                                <tr>
                                    <td class="center">{{ host_comment.created|timesince }} 前</td>

                                    <td>
                                        <a href="{{ host_comment.host.get_absolute_url }}">{{ host_comment.host.ip }}</a>
                                    </td>
                                    <td class="hidden-xs">
                                        {{ host_comment.body }}
                                    </td>
                                    <td class="hidden-480">{{ host_comment.host }}</td>
                                    <td>{{ host_comment.author }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '主机分组情况'
            },
            tooltip: {},
            legend: {
                data:['主机数量']
            },
            xAxis: {
                data: ["CRM","TRM","OA","TUNE","WMS","Manage"]
            },
            yAxis: {},
            series: [{
                name: '数量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>


{% endblock main %}